set(EDUPALS_BASE_FOUND TRUE)

set(EDUPALS_BASE_VERSION_MAJOR 1)
set(EDUPALS_BASE_VERSION_MINOR 0)
set(EDUPALS_BASE_VERSION 1.0)
set(EDUPALS_BASE_VERSION_STRING "1.0")

set(EDUPALS_BASE_INCLUDE_DIRS "/usr/include/edupals/base/")
set(EDUPALS_BASE_LIBRARIES "-ledupals-base")